name: Build
on:
  push:
    branches:
      - main
      - preview
  release:
    types:
      - published
  workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'npm'
            - run: npm ci
            - name: Assets
              uses: actions/cache@v4
              with:
                path: data
                key: data-${{github.ref_name}}
                restore-keys: |
                              data-main
            - run: ./makeBundle.sh
            - name: Archive production artifacts
              uses: actions/upload-artifact@v4
              with:
                name: tappdex
                path: |
                      dist
    create-release:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            contents: write
        if: github.ref_type == 'tag' || github.ref_name == 'automation'
        steps:
            - uses: actions/download-artifact@v4
              with:
                name: tappdex
            - run: zip -r tappdex.zip *
            - name: Create release
              uses: softprops/action-gh-release@v2
              with:
                files: tappdex.zip
                # draft: true
                
    publish-pages:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            id-token: write
            pages: write
        if: github.ref_name == 'preview' || github.ref_name == 'automation'
        steps:
            - uses: actions/download-artifact@v4
              with:
                name: tappdex
            - name: Upload pages content
              uses: actions/upload-pages-artifact@v3
              with:
                path: .
            - name: Deploy pages content
              uses: actions/deploy-pages@v4
                
    
                      